# -*- coding: utf-8 -*-
"""C14230230-pertemuan6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lViumsbnx055GFobjbxNPNIlUEZcwH4B
"""

# https://docs.google.com/document/d/1aY92rers403xPiYfAJbASbCdTI4YInXPSPfKZQPetPI/edit?tab=t.0

# Soal 1
from collections import deque

def timeCount(tickets, k):
    queue = deque([(i, t) for i, t in enumerate(tickets)])
    totalTime = 0
    while True:
        # print("Awal: ", queue)
        position, ticketsLeft = queue.popleft()
        if position == k and ticketsLeft == 1:
          totalTime += 1
          break
        if ticketsLeft-1 == 0: #klo val = 0, di pop depan
          if queue and queue[0][1] == 0:
            queue.popleft()
        else:
          queue.append((position, ticketsLeft - 1))
        totalTime += 1
        # print(queue)
    return totalTime

tickets = [2, 3, 2]
k = 2
print(timeCount(tickets, k))

tickets = [5, 1, 1, 1]
k = 0
print(timeCount(tickets, k))

# Coret"
# 32*1, 2*12, 121*, 21*0, 1*1, 1
# 1114*, 114*0, 14*00, 4*000, 3, 2, 1, 0

# Soal 2



def studentsLeft(students, sandwiches):
    studentQueue = deque(students)
    sandwichQueue = deque(sandwiches)
    count = 0
    while studentQueue:
        if studentQueue[0] == sandwichQueue[0]:
            studentQueue.popleft()
            sandwichQueue.popleft()
            count = 0
        else:
            studentQueue.append(studentQueue.popleft())
            count += 1
            if count == len(students):
                break
    return len(studentQueue)




students = [1, 1, 0, 0]
sandwiches = [0, 1, 0, 1]
print(studentsLeft(students, sandwiches))

students = [1, 1, 1, 0, 0, 1]
sandwiches = [1, 0, 0, 0, 1, 1]
print(studentsLeft(students, sandwiches))
